import { Listing } from '@/types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Vintage Leather Jacket',
    description: 'Classic brown leather jacket, excellent condition',
    price: 120,
    category: 'fashion',
    location: 'Orchard',
    condition: 'excellent',
    timeAgo: '2 hours ago',
    imageUrl: 'https://picsum.photos/seed/1/400/400?category=fashion',
    hasVideo: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    userId: 'user1',
  },
  {
    id: '2',
    title: 'iPhone 14 Pro Max',
    description: 'Like new, minimal scratches',
    price: 950,
    category: 'electronics',
    location: 'Marina Bay',
    condition: 'like-new',
    timeAgo: '5 hours ago',
    imageUrl: 'https://picsum.photos/seed/2/400/400?category=electronics',
    hasVideo: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    userId: 'user2',
  },
  {
    id: '3',
    title: 'IKEA Dining Table',
    description: 'Walnut finish, seats 6, good condition',
    price: 250,
    category: 'furniture',
    location: 'Jurong',
    condition: 'good',
    timeAgo: '1 day ago',
    imageUrl: 'https://picsum.photos/seed/3/400/400?category=furniture',
    hasVideo: false,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    userId: 'user3',
  },
  {
    id: '4',
    title: 'Baby Stroller - Safety 1st',
    description: 'Compact, folds easily, all wheels working',
    price: 80,
    category: 'baby',
    location: 'Tampines',
    condition: 'good',
    timeAgo: '3 days ago',
    imageUrl: 'https://picsum.photos/seed/4/400/400?category=baby',
    hasVideo: false,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 'user4',
  },
  {
    id: '5',
    title: 'Harry Potter Complete Series',
    description: '7 books, all hardcover, dust jackets included',
    price: 45,
    category: 'books',
    location: 'Bukit Merah',
    condition: 'excellent',
    timeAgo: '2 days ago',
    imageUrl: 'https://picsum.photos/seed/5/400/400?category=books',
    hasVideo: false,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 'user5',
  },
  {
    id: '6',
    title: 'Canon EOS R5 Mirrorless Camera',
    description: 'Professional grade, 2 batteries, memory cards',
    price: 2500,
    category: 'electronics',
    location: 'CBD',
    condition: 'excellent',
    timeAgo: '6 hours ago',
    imageUrl: 'https://picsum.photos/seed/6/400/400?category=electronics',
    hasVideo: true,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    userId: 'user6',
  },
  {
    id: '7',
    title: 'Supreme Box Logo Hoodie',
    description: 'Rare piece, authentic, worn once',
    price: 450,
    category: 'fashion',
    location: 'Bugis',
    condition: 'like-new',
    timeAgo: '4 hours ago',
    imageUrl: 'https://picsum.photos/seed/7/400/400?category=fashion',
    hasVideo: false,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    userId: 'user7',
  },
  {
    id: '8',
    title: 'Office Chair - Herman Miller',
    description: 'Ergonomic, adjustable lumbar support, like new',
    price: 400,
    category: 'furniture',
    location: 'Novena',
    condition: 'like-new',
    timeAgo: '1 day ago',
    imageUrl: 'https://picsum.photos/seed/8/400/400?category=furniture',
    hasVideo: false,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    userId: 'user8',
  },
  {
    id: '9',
    title: 'Baby Crib with Mattress',
    description: 'Wooden crib, includes organic mattress',
    price: 150,
    category: 'baby',
    location: 'Punggol',
    condition: 'good',
    timeAgo: '5 days ago',
    imageUrl: 'https://picsum.photos/seed/9/400/400?category=baby',
    hasVideo: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 'user9',
  },
  {
    id: '10',
    title: 'Design Books Bundle',
    description: 'Logo Design, Typography, UX Design books',
    price: 60,
    category: 'books',
    location: 'Holland',
    condition: 'excellent',
    timeAgo: '1 week ago',
    imageUrl: 'https://picsum.photos/seed/10/400/400?category=books',
    hasVideo: false,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 'user10',
  },
  {
    id: '11',
    title: 'Apple Watch Series 8',
    description: 'Gold aluminium, cellular, scratched screen protector',
    price: 380,
    category: 'electronics',
    location: 'Suntec',
    condition: 'good',
    timeAgo: '12 hours ago',
    imageUrl: 'https://picsum.photos/seed/11/400/400?category=electronics',
    hasVideo: false,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    userId: 'user11',
  },
  {
    id: '12',
    title: 'Gucci Marmont Belt',
    description: 'Authentic, worn a few times, with original box',
    price: 380,
    category: 'fashion',
    location: 'Tanglin',
    condition: 'like-new',
    timeAgo: '8 hours ago',
    imageUrl: 'https://picsum.photos/seed/12/400/400?category=fashion',
    hasVideo: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    userId: 'user12',
  },
];
